/**
 * Writes src/i18n/dictionary.generated.ts from the ES/EV_ES maps in
 * ../fc-data.js, reusing the same sandbox loader the seed uses.
 *
 *   pnpm gen:dictionary
 *
 * This is UI chrome only — nav labels, button text, section headings. Content
 * (listings, events, stories) is localized in Payload and arrives already
 * translated; running it through t() again would be a double-translate.
 *
 * Generated rather than hand-copied so a re-pull from Claude Design can't
 * silently desync the two.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { loadFCBase } from '../seed/load-fc-data'

const dirname = path.dirname(fileURLToPath(import.meta.url))
const base = loadFCBase()

const merged: Record<string, string> = { ...(base.ES ?? {}), ...(base.EV_ES ?? {}) }
const keys = Object.keys(merged).sort()

const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(merged[k])},`).join('\n')

const out = `/* eslint-disable */
/**
 * GENERATED by \`pnpm gen:dictionary\` from ../fc-data.js — do not edit by hand.
 *
 * The keys ARE the English strings. ${keys.filter((k) => /[.:]/.test(k)).length} of them contain "." or ":",
 * which is why this is a flat Record and not an i18n library with key paths —
 * that exact assumption has already bitten this project once.
 */
export const ES: Record<string, string> = {
${body}
}

export const ES_KEY_COUNT = ${keys.length}
`

const target = path.join(dirname, 'dictionary.generated.ts')
fs.writeFileSync(target, out)
console.log(`wrote ${keys.length} keys to ${path.relative(process.cwd(), target)}`)
