/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    cities: City;
    categories: Category;
    'event-kinds': EventKind;
    listings: Listing;
    stories: Story;
    events: Event;
    'weekly-events': WeeklyEvent;
    spotlights: Spotlight;
    subscribers: Subscriber;
    'listing-requests': ListingRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'event-kinds': EventKindsSelect<false> | EventKindsSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'weekly-events': WeeklyEventsSelect<false> | WeeklyEventsSelect<true>;
    spotlights: SpotlightsSelect<false> | SpotlightsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'listing-requests': ListingRequestsSelect<false> | ListingRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    'site-settings': SiteSetting;
    'about-page': AboutPage;
    'list-your-spot-page': ListYourSpotPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'list-your-spot-page': ListYourSpotPageSelect<false> | ListYourSpotPageSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Photographer or source, where there is one.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Set in caps. Not translated — proper noun.
   */
  name: string;
  /**
   * The tagline under the name, e.g. "Calle Ocho Forever".
   */
  sub?: string | null;
  /**
   * The paragraph on the city page.
   */
  blurb?: string | null;
  /**
   * Order in the nav tabs and city lists. Source order: Hialeah, Miami Lakes, Little Havana.
   */
  order?: number | null;
  /**
   * Index into the cast array, picking which character represents the city. Vestigial in the source — every city sets `solo`, which wins over it.
   */
  lead?: number | null;
  /**
   * City accent hex, e.g. #FF2E88.
   */
  accent?: string | null;
  /**
   * Backdrop hex behind the mascot cast.
   */
  castBg?: string | null;
  /**
   * City hero. The static site hand-rolled a responsive set via PHOTOS/pickPhoto; Payload generates the sizes from this single source instead.
   */
  photo?: (number | null) | Media;
  /**
   * CSS object-position, e.g. "center 45%". Blank means center.
   */
  photoPos?: string | null;
  /**
   * The single mascot used in compact spots.
   */
  solo?: (number | null) | Media;
  /**
   * e.g. RAFA. Not translated — a name.
   */
  soloName?: string | null;
  /**
   * How many characters the group art depicts.
   */
  castCount?: number | null;
  /**
   * Aspect ratio of the group art, e.g. "1122 / 975".
   */
  groupAR?: string | null;
  /**
   * Crops the mascot head out of the group art for the city tab avatar.
   */
  headOffset?: {
    /**
     * height, e.g. 440%
     */
    h?: string | null;
    /**
     * left, e.g. -50%
     */
    l?: string | null;
    /**
     * top, e.g. -11%
     */
    t?: string | null;
  };
  /**
   * The mascot busts shown on the city page.
   */
  cast?:
    | {
        image?: (number | null) | Media;
        /**
         * e.g. "RAFA & YOLI". Not translated — names.
         */
        name?: string | null;
        /**
         * Backdrop hex for this bust.
         */
        bg?: string | null;
        /**
         * Stacking order.
         */
        z?: number | null;
        /**
         * This image shows the whole cast, not one character.
         */
        group?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Shown on the filter chips. Set in caps, e.g. BARS & RESTAURANTS.
   */
  label: string;
  /**
   * Chip display order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-kinds".
 */
export interface EventKind {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  label: string;
  /**
   * CSS background — a hex colour or a full linear-gradient(...) string. Used as the chip/badge fill.
   */
  bg: string;
  /**
   * Foreground hex that reads against bg, e.g. #FFF6E5 or #0C0F14.
   */
  ink: string;
  /**
   * Chip display order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Not translated — the business name is the business name.
   */
  name: string;
  city: number | City;
  category: number | Category;
  /**
   * Cross street or neighbourhood, e.g. "SW 8th St".
   */
  hood?: string | null;
  /**
   * The one-line pitch on the card. Fully translated in the source.
   */
  tag?: string | null;
  rating?: number | null;
  reviews?: number | null;
  /**
   * How much of this record is actually known. `unsourced` is the original design content, whose phone and hours were synthesized from the array index — it is not a smaller version of `ready`, it is a different kind of data. Filter on this before publishing anything.
   */
  publicationStatus: 'ready' | 'needs_owner_confirmation' | 'unsourced';
  /**
   * Paying member — earns the badge.
   */
  member?: boolean | null;
  /**
   * Art direction for the empty photo slot, e.g. "Cantina bar". Shown as the placeholder label until a real photo lands.
   */
  imageHint?: string | null;
  /**
   * Hero first, then the detail-page gallery. Empty for now by design.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Only el-gallo has authored detail. Everything else is intentionally blank — the old site faked these values from the array index.
   */
  detail?: {
    story?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    quote?: string | null;
    /**
     * e.g. "RIGO PEÑA, OWNER". Not translated — a name and a role.
     */
    quoteBy?: string | null;
    /**
     * The mascot-crew aside on the detail page.
     */
    crewLine?: string | null;
    address?: string | null;
    phone?: string | null;
    /**
     * Bare host, no scheme.
     */
    site?: string | null;
    cta?: string | null;
    email?: string | null;
    /**
     * Full profile URL. For the researched listings this is more reliable than the website — 10 of 11 have one, 9 have a site, and one of those sites is down.
     */
    instagram?: string | null;
    hours?:
      | {
          /**
           * e.g. "Mon – Wed"
           */
          d: string;
          /**
           * e.g. "11am – 11pm"
           */
          t: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Empty means authored design content rather than researched. The Business page renders hours only at `high` or empty; anything less shows a "call to confirm" line instead, because wrong hours generate owner complaints.
     */
    hoursConfidence?: ('high' | 'medium' | 'low' | 'none') | null;
    /**
     * Where sources disagreed. Kept rather than resolved — picking one silently is what this record exists to prevent.
     */
    hoursConflicts?:
      | {
          source: string;
          detail: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Only populated for imported listings. This is what separates a sourced record from a plausible one — if you edit a field above, add or update the source here too, or the record quietly stops being auditable.
   */
  research?: {
    /**
     * The year the business actually opened or was founded, with a source. NOT the Florida corporate filing date — that is a registration event and several businesses here filed decades after opening. Blank means unknown, which is a fact, not an omission to fill in.
     */
    established?: string | null;
    /**
     * Why the date is what it is, or why there is none.
     */
    establishedNote?: string | null;
    /**
     * e.g. Peruvian, Ceviche, Seafood.
     */
    cuisine?: string[] | null;
    /**
     * The dishes a first-timer comes for.
     */
    signatureItems?: string[] | null;
    /**
     * What must be asked of the owner before this listing is complete. Non-empty is what `needs owner confirmation` means.
     */
    blockingGaps?: string[] | null;
    sources?:
      | {
          url: string;
          title?: string | null;
          publisher?: string | null;
          /**
           * e.g. press, owned, aggregator.
           */
          type?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Registered entity name, where it differs from the trading name.
     */
    legalEntity?: string | null;
    /**
     * The dossier this record was generated from, e.g. research/hialeah/molina.md in the flamingo-city repo.
     */
    sourceFile?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  title: string;
  /**
   * The standfirst under the headline.
   */
  dek?: string | null;
  /**
   * e.g. "LITTLE HAVANA · SINCE 1994".
   */
  kicker?: string | null;
  /**
   * e.g. "6 MIN READ".
   */
  readTime?: string | null;
  /**
   * e.g. "AS TOLD TO FLAMINGO COUNTY".
   */
  byline?: string | null;
  /**
   * The business this story is about. Drives the "see the listing" CTA.
   */
  listing?: (number | null) | Listing;
  /**
   * e.g. "SEE THE LISTING →".
   */
  bizCta?: string | null;
  cover?: (number | null) | Media;
  coverHint?: string | null;
  coverCap?: string | null;
  blocks?:
    | (
        | {
            /**
             * The first character renders as a drop cap.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dropCap';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            /**
             * e.g. "RIGO PEÑA, OWNER". Not translated — a name and a role.
             */
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pullQuote';
          }
        | {
            image?: (number | null) | Media;
            /**
             * Art direction for the empty slot. The image-slot sidecar was never created, so every story image is still a labelled placeholder.
             */
            hint?: string | null;
            caption?: string | null;
            /**
             * CSS aspect-ratio. Defaults to 16 / 9.
             */
            aspectRatio?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            a?: {
              image?: (number | null) | Media;
              /**
               * Art direction for the empty slot. The image-slot sidecar was never created, so every story image is still a labelled placeholder.
               */
              hint?: string | null;
              caption?: string | null;
            };
            b?: {
              image?: (number | null) | Media;
              /**
               * Art direction for the empty slot. The image-slot sidecar was never created, so every story image is still a labelled placeholder.
               */
              hint?: string | null;
              caption?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagePair';
          }
        | {
            title: string;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutNote';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionBreak';
          }
      )[]
    | null;
  /**
   * The practical sign-off after the body. KNOWN GAP: all 3 stories are missing a Spanish outro in the source dictionary — the old site silently rendered English here on ES pages. Worth writing.
   */
  outro?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  title: string;
  date: string;
  /**
   * Display string as written, e.g. "9PM–1AM". Not parsed. Localized because it is not always a clock reading — an event whose time is not settled says so in words ("Por confirmar"), and that has to translate.
   */
  timeLabel?: string | null;
  kind: number | EventKind;
  venueType: 'listing' | 'place';
  listing?: (number | null) | Listing;
  /**
   * e.g. "Máximo Gómez Park".
   */
  place?: string | null;
  hood?: string | null;
  city?: (number | null) | City;
  /**
   * Eligible for the "on deck" spotlight.
   */
  star?: boolean | null;
  /**
   * Seed count only. Not a live tally — there are no accounts yet.
   */
  going?: number | null;
  /**
   * A price/entry label, not a boolean — e.g. "NO COVER BEFORE 10", "$12 A PLATE", "FREE TO WATCH".
   */
  freeLabel?: string | null;
  /**
   * The longer blurb on the event page. Only starred events have one.
   */
  note?: string | null;
  image?: (number | null) | Media;
  /**
   * Art direction for the empty photo slot.
   */
  imageHint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-events".
 */
export interface WeeklyEvent {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  title: string;
  /**
   * Day of week, matching JS getDay(): 0 = Sunday.
   */
  dow: '0' | '1' | '2' | '3' | '4' | '5' | '6';
  /**
   * Display string, e.g. "8PM" or "5–9PM".
   */
  time?: string | null;
  listing: number | Listing;
  kind: number | EventKind;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spotlights".
 */
export interface Spotlight {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  city: number | City;
  listing: number | Listing;
  /**
   * The kicker above the card, e.g. "CANTINA · LIVE MUSIC".
   */
  kind?: string | null;
  /**
   * The offer, e.g. "2-for-1 mojitos, Thursday to Saturday, 7–9pm".
   */
  deal?: string | null;
  blurb?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * Which version of the site they signed up from.
   */
  lang?: ('en' | 'es') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-requests".
 */
export interface ListingRequest {
  id: number;
  status?: ('new' | 'contacted' | 'listed' | 'declined') | null;
  business: string;
  owner?: string | null;
  phone: string;
  email?: string | null;
  city?: (number | null) | City;
  category?: (number | null) | Category;
  /**
   * What they told us about the place.
   */
  story?: string | null;
  /**
   * Which version of the site they submitted from.
   */
  lang?: ('en' | 'es') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'event-kinds';
        value: number | EventKind;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'weekly-events';
        value: number | WeeklyEvent;
      } | null)
    | ({
        relationTo: 'spotlights';
        value: number | Spotlight;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'listing-requests';
        value: number | ListingRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  sub?: T;
  blurb?: T;
  order?: T;
  lead?: T;
  accent?: T;
  castBg?: T;
  photo?: T;
  photoPos?: T;
  solo?: T;
  soloName?: T;
  castCount?: T;
  groupAR?: T;
  headOffset?:
    | T
    | {
        h?: T;
        l?: T;
        t?: T;
      };
  cast?:
    | T
    | {
        image?: T;
        name?: T;
        bg?: T;
        z?: T;
        group?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-kinds_select".
 */
export interface EventKindsSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  bg?: T;
  ink?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  city?: T;
  category?: T;
  hood?: T;
  tag?: T;
  rating?: T;
  reviews?: T;
  publicationStatus?: T;
  member?: T;
  imageHint?: T;
  gallery?: T;
  detail?:
    | T
    | {
        story?:
          | T
          | {
              text?: T;
              id?: T;
            };
        quote?: T;
        quoteBy?: T;
        crewLine?: T;
        address?: T;
        phone?: T;
        site?: T;
        cta?: T;
        email?: T;
        instagram?: T;
        hours?:
          | T
          | {
              d?: T;
              t?: T;
              id?: T;
            };
        hoursConfidence?: T;
        hoursConflicts?:
          | T
          | {
              source?: T;
              detail?: T;
              id?: T;
            };
      };
  research?:
    | T
    | {
        established?: T;
        establishedNote?: T;
        cuisine?: T;
        signatureItems?: T;
        blockingGaps?: T;
        sources?:
          | T
          | {
              url?: T;
              title?: T;
              publisher?: T;
              type?: T;
              id?: T;
            };
        legalEntity?: T;
        sourceFile?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  dek?: T;
  kicker?: T;
  readTime?: T;
  byline?: T;
  listing?: T;
  bizCta?: T;
  cover?: T;
  coverHint?: T;
  coverCap?: T;
  blocks?:
    | T
    | {
        dropCap?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        pullQuote?:
          | T
          | {
              text?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              hint?: T;
              caption?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        imagePair?:
          | T
          | {
              a?:
                | T
                | {
                    image?: T;
                    hint?: T;
                    caption?: T;
                  };
              b?:
                | T
                | {
                    image?: T;
                    hint?: T;
                    caption?: T;
                  };
              id?: T;
              blockName?: T;
            };
        calloutNote?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        sectionBreak?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  outro?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  date?: T;
  timeLabel?: T;
  kind?: T;
  venueType?: T;
  listing?: T;
  place?: T;
  hood?: T;
  city?: T;
  star?: T;
  going?: T;
  freeLabel?: T;
  note?: T;
  image?: T;
  imageHint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-events_select".
 */
export interface WeeklyEventsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  dow?: T;
  time?: T;
  listing?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spotlights_select".
 */
export interface SpotlightsSelect<T extends boolean = true> {
  slug?: T;
  city?: T;
  listing?: T;
  kind?: T;
  deal?: T;
  blurb?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-requests_select".
 */
export interface ListingRequestsSelect<T extends boolean = true> {
  status?: T;
  business?: T;
  owner?: T;
  phone?: T;
  email?: T;
  city?: T;
  category?: T;
  story?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  showSpotlight?: boolean | null;
  showRatings?: boolean | null;
  memberBadges?: boolean | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * The skyline shot behind the headline.
   */
  heroPhoto?: (number | null) | Media;
  /**
   * The three mascots together.
   */
  heroCast?: (number | null) | Media;
  /**
   * Backdrop hex behind the group art.
   */
  heroCastBg?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  kicker?: string | null;
  h1a?: string | null;
  h1b?: string | null;
  intro?: string | null;
  photo?: (number | null) | Media;
  photoHint?: string | null;
  founderKicker?: string | null;
  founderP1?: string | null;
  founderP2?: string | null;
  founderSig?: string | null;
  founderTag?: string | null;
  howH?: string | null;
  steps?:
    | {
        /**
         * Step number.
         */
        n?: string | null;
        /**
         * Hex or linear-gradient(...) for the step chip.
         */
        bg?: string | null;
        t?: string | null;
        d?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaH?: string | null;
  ctaP?: string | null;
  ctaBtn?: string | null;
  reachH?: string | null;
  reachP?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "list-your-spot-page".
 */
export interface ListYourSpotPage {
  id: number;
  /**
   * The membership perk chips.
   */
  perks?:
    | {
        t: string;
        d: string;
        /**
         * Named explicitly. The old site derived this from array position, so reordering perks reshuffled the icons.
         */
        icon?: ('map-pin' | 'nfc' | 'qr-code' | 'newspaper' | 'megaphone' | 'bird') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on every non-food listing detail page. Page copy, identical for all of them — not per-business data.
   */
  services?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  showSpotlight?: T;
  showRatings?: T;
  memberBadges?: T;
  contactEmail?: T;
  contactPhone?: T;
  heroPhoto?: T;
  heroCast?: T;
  heroCastBg?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  kicker?: T;
  h1a?: T;
  h1b?: T;
  intro?: T;
  photo?: T;
  photoHint?: T;
  founderKicker?: T;
  founderP1?: T;
  founderP2?: T;
  founderSig?: T;
  founderTag?: T;
  howH?: T;
  steps?:
    | T
    | {
        n?: T;
        bg?: T;
        t?: T;
        d?: T;
        id?: T;
      };
  ctaH?: T;
  ctaP?: T;
  ctaBtn?: T;
  reachH?: T;
  reachP?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "list-your-spot-page_select".
 */
export interface ListYourSpotPageSelect<T extends boolean = true> {
  perks?:
    | T
    | {
        t?: T;
        d?: T;
        icon?: T;
        id?: T;
      };
  services?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}