/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    cities: City;
    categories: Category;
    'event-kinds': EventKind;
    listings: Listing;
    stories: Story;
    events: Event;
    'weekly-events': WeeklyEvent;
    spotlights: Spotlight;
    subscribers: Subscriber;
    'listing-requests': ListingRequest;
    members: Member;
    'hq-events': HqEvent;
    'hq-tasks': HqTask;
    'hq-media': HqMedia;
    'hq-social-drafts': HqSocialDraft;
    'hq-social-stats': HqSocialStat;
    'hq-clicks': HqClick;
    'hq-publish-requests': HqPublishRequest;
    'hq-chat-turns': HqChatTurn;
    'hq-visits': HqVisit;
    'hq-experiments': HqExperiment;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'event-kinds': EventKindsSelect<false> | EventKindsSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'weekly-events': WeeklyEventsSelect<false> | WeeklyEventsSelect<true>;
    spotlights: SpotlightsSelect<false> | SpotlightsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'listing-requests': ListingRequestsSelect<false> | ListingRequestsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'hq-events': HqEventsSelect<false> | HqEventsSelect<true>;
    'hq-tasks': HqTasksSelect<false> | HqTasksSelect<true>;
    'hq-media': HqMediaSelect<false> | HqMediaSelect<true>;
    'hq-social-drafts': HqSocialDraftsSelect<false> | HqSocialDraftsSelect<true>;
    'hq-social-stats': HqSocialStatsSelect<false> | HqSocialStatsSelect<true>;
    'hq-clicks': HqClicksSelect<false> | HqClicksSelect<true>;
    'hq-publish-requests': HqPublishRequestsSelect<false> | HqPublishRequestsSelect<true>;
    'hq-chat-turns': HqChatTurnsSelect<false> | HqChatTurnsSelect<true>;
    'hq-visits': HqVisitsSelect<false> | HqVisitsSelect<true>;
    'hq-experiments': HqExperimentsSelect<false> | HqExperimentsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    'site-settings': SiteSetting;
    'about-page': AboutPage;
    'list-your-spot-page': ListYourSpotPage;
    'hq-playbook': HqPlaybook;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'list-your-spot-page': ListYourSpotPageSelect<false> | ListYourSpotPageSelect<true>;
    'hq-playbook': HqPlaybookSelect<false> | HqPlaybookSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      morningBrief: TaskMorningBrief;
      socialStats: TaskSocialStats;
      eveningWrap: TaskEveningWrap;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Photographer or source, where there is one. Shown wherever the photo is.
   */
  credit?: string | null;
  /**
   * Public domain, or Creative Commons that allows commercial reuse. Never non-commercial (NC) or no-derivatives (ND): the cards crop the photo and set type on it.
   */
  license?:
    | (
        | 'public-domain'
        | 'cc0'
        | 'cc-by-2.0'
        | 'cc-by-3.0'
        | 'cc-by-4.0'
        | 'cc-by-sa-2.0'
        | 'cc-by-sa-3.0'
        | 'cc-by-sa-4.0'
      )
    | null;
  /**
   * The licence deed, e.g. https://creativecommons.org/licenses/by/2.0/
   */
  licenseUrl?: string | null;
  /**
   * The photo’s description page (Commons, Flickr, loc.gov), where its licence is stated.
   */
  sourceUrl?: string | null;
  /**
   * The file was cropped or edited. CC 3.0 and 4.0 require saying so; the credit adds “cropped”.
   */
  modified?: boolean | null;
  /**
   * Made by Flamingo County. Empty for a licensed photo from an archive.
   */
  origin?: ('own-illustration' | 'own-photo') | null;
  /**
   * What our artwork was drawn from, as the credit says it, e.g. "basada en fotos del Historic American Buildings Survey (dominio público)".
   */
  basedOn?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Set in caps. Not translated — proper noun.
   */
  name: string;
  /**
   * The tagline under the name, e.g. "Calle Ocho Forever".
   */
  sub?: string | null;
  /**
   * The paragraph on the city page.
   */
  blurb?: string | null;
  /**
   * Order in the nav tabs and city lists. Source order: Hialeah, Miami Lakes, Little Havana.
   */
  order?: number | null;
  /**
   * Index into the cast array, picking which character represents the city. Vestigial in the source — every city sets `solo`, which wins over it.
   */
  lead?: number | null;
  /**
   * City accent hex, e.g. #FF2E88.
   */
  accent?: string | null;
  /**
   * Backdrop hex behind the mascot cast.
   */
  castBg?: string | null;
  /**
   * City hero. The static site hand-rolled a responsive set via PHOTOS/pickPhoto; Payload generates the sizes from this single source instead.
   */
  photo?: (number | null) | Media;
  /**
   * CSS object-position, e.g. "center 45%". Blank means center.
   */
  photoPos?: string | null;
  /**
   * The single mascot used in compact spots.
   */
  solo?: (number | null) | Media;
  /**
   * e.g. RAFA. Not translated — a name.
   */
  soloName?: string | null;
  /**
   * How many characters the group art depicts.
   */
  castCount?: number | null;
  /**
   * Aspect ratio of the group art, e.g. "1122 / 975".
   */
  groupAR?: string | null;
  /**
   * Crops the mascot head out of the group art for the city tab avatar.
   */
  headOffset?: {
    /**
     * height, e.g. 440%
     */
    h?: string | null;
    /**
     * left, e.g. -50%
     */
    l?: string | null;
    /**
     * top, e.g. -11%
     */
    t?: string | null;
  };
  /**
   * The mascot busts shown on the city page.
   */
  cast?:
    | {
        image?: (number | null) | Media;
        /**
         * e.g. "RAFA & YOLI". Not translated — names.
         */
        name?: string | null;
        /**
         * Backdrop hex for this bust.
         */
        bg?: string | null;
        /**
         * Stacking order.
         */
        z?: number | null;
        /**
         * This image shows the whole cast, not one character.
         */
        group?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Shown on the filter chips. Set in caps, e.g. BARS & RESTAURANTS.
   */
  label: string;
  /**
   * Chip display order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-kinds".
 */
export interface EventKind {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  label: string;
  /**
   * CSS background — a hex colour or a full linear-gradient(...) string. Used as the chip/badge fill.
   */
  bg: string;
  /**
   * Foreground hex that reads against bg, e.g. #FFF6E5 or #0C0F14.
   */
  ink: string;
  /**
   * Chip display order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  /**
   * Not translated — the business name is the business name.
   */
  name: string;
  city: number | City;
  category: number | Category;
  /**
   * Cross street or neighbourhood, e.g. "SW 8th St".
   */
  hood?: string | null;
  /**
   * The one-line pitch on the card. Fully translated in the source.
   */
  tag?: string | null;
  /**
   * The 40–60 word answer the page opens with: what this place is, where, and what it is known for, in plain sentences an answer engine can quote. Only facts this record already holds with a source. A founding year whose research note says to attribute it must say who says so ("since 1982, according to Burger Beast"). No prices. Empty shows a short line built from the name, category, neighborhood and address instead.
   */
  answer?: string | null;
  rating?: number | null;
  reviews?: number | null;
  /**
   * How much of this record is actually known. `unsourced` is the original design content, whose phone and hours were synthesized from the array index — it is not a smaller version of `ready`, it is a different kind of data. Filter on this before publishing anything.
   */
  publicationStatus: 'ready' | 'needs_owner_confirmation' | 'unsourced';
  /**
   * Partner — earns the PARTNER badge.
   */
  member?: boolean | null;
  /**
   * The day the facts on this page were last checked against their sources. Set it when you actually check, never as a formality: answer engines read it as a freshness claim. Empty means nobody has.
   */
  lastVerifiedAt?: string | null;
  /**
   * Who or what did that check, e.g. "Owner, by phone" or "Research dossier".
   */
  verifiedBy?: string | null;
  /**
   * Art direction for the empty photo slot, e.g. "Cantina bar". Shown as the placeholder label until a real photo lands.
   */
  imageHint?: string | null;
  /**
   * Hero first, then the detail-page gallery. Empty for now by design.
   */
  gallery?: (number | Media)[] | null;
  /**
   * The mark, on transparency, for drawing over somebody else's photograph — an event hero shows the people at the event and nothing that names the room. Not a substitute for `gallery[0]`, which is the storefront: nothing uses this as a hero. Leave it empty unless there is artwork with the background actually removed; a logo on a white card looks like a mistake once it is sitting on a photo.
   */
  logo?: (number | null) | Media;
  /**
   * Only el-gallo has authored detail. Everything else is intentionally blank — the old site faked these values from the array index.
   */
  detail?: {
    story?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    quote?: string | null;
    /**
     * e.g. "RIGO PEÑA, OWNER". Not translated — a name and a role.
     */
    quoteBy?: string | null;
    /**
     * The mascot-crew aside on the detail page.
     */
    crewLine?: string | null;
    address?: string | null;
    phone?: string | null;
    /**
     * Bare host, no scheme.
     */
    site?: string | null;
    cta?: string | null;
    email?: string | null;
    /**
     * Full profile URL. For the researched listings this is more reliable than the website — 10 of 11 have one, 9 have a site, and one of those sites is down.
     */
    instagram?: string | null;
    hours?:
      | {
          /**
           * e.g. "Mon – Wed"
           */
          d: string;
          /**
           * e.g. "11am – 11pm"
           */
          t: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Empty means authored design content rather than researched. The Business page renders hours only at `high` or empty; anything less shows a "call to confirm" line instead, because wrong hours generate owner complaints.
     */
    hoursConfidence?: ('high' | 'medium' | 'low' | 'none') | null;
    /**
     * Where sources disagreed. Kept rather than resolved — picking one silently is what this record exists to prevent.
     */
    hoursConflicts?:
      | {
          source: string;
          detail: string;
          id?: string | null;
        }[]
      | null;
    /**
     * The schedule as data, from the same source as `hours`. A closing time earlier than the opening time means past midnight. Only published as structured data when `hoursConfidence` is high — a guessed schedule in Google is worse than none.
     */
    openingHours?:
      | {
          days: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday')[];
          /**
           * 24-hour HH:mm
           */
          opens: string;
          /**
           * 24-hour HH:mm
           */
          closes: string;
          id?: string | null;
        }[]
      | null;
    /**
     * The URL the schedule was read from.
     */
    hoursSource?: string | null;
  };
  /**
   * Only populated for imported listings. This is what separates a sourced record from a plausible one — if you edit a field above, add or update the source here too, or the record quietly stops being auditable.
   */
  research?: {
    /**
     * The year the business actually opened or was founded, with a source. NOT the Florida corporate filing date — that is a registration event and several businesses here filed decades after opening. Blank means unknown, which is a fact, not an omission to fill in.
     */
    established?: string | null;
    /**
     * Why the date is what it is, or why there is none.
     */
    establishedNote?: string | null;
    /**
     * e.g. Peruvian, Ceviche, Seafood.
     */
    cuisine?: string[] | null;
    /**
     * The dishes a first-timer comes for.
     */
    signatureItems?: string[] | null;
    /**
     * What must be asked of the owner before this listing is complete. Non-empty is what `needs owner confirmation` means.
     */
    blockingGaps?: string[] | null;
    sources?:
      | {
          url: string;
          title?: string | null;
          publisher?: string | null;
          /**
           * e.g. press, owned, aggregator.
           */
          type?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Registered entity name, where it differs from the trading name.
     */
    legalEntity?: string | null;
    /**
     * The dossier this record was generated from, e.g. research/hialeah/molina.md in the flamingo-city repo.
     */
    sourceFile?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  title: string;
  /**
   * The standfirst under the headline.
   */
  dek?: string | null;
  /**
   * e.g. "LITTLE HAVANA · SINCE 1994".
   */
  kicker?: string | null;
  /**
   * e.g. "6 MIN READ".
   */
  readTime?: string | null;
  /**
   * e.g. "AS TOLD TO FLAMINGO COUNTY".
   */
  byline?: string | null;
  /**
   * The business this story is about. Drives the "see the listing" CTA.
   */
  listing?: (number | null) | Listing;
  /**
   * e.g. "SEE THE LISTING →".
   */
  bizCta?: string | null;
  cover?: (number | null) | Media;
  coverHint?: string | null;
  coverCap?: string | null;
  blocks?:
    | (
        | {
            /**
             * The first character renders as a drop cap.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dropCap';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            /**
             * e.g. "RIGO PEÑA, OWNER". Not translated — a name and a role.
             */
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pullQuote';
          }
        | {
            image?: (number | null) | Media;
            /**
             * Art direction for the empty slot. The image-slot sidecar was never created, so every story image is still a labelled placeholder.
             */
            hint?: string | null;
            caption?: string | null;
            /**
             * CSS aspect-ratio. Defaults to 16 / 9.
             */
            aspectRatio?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            a?: {
              image?: (number | null) | Media;
              /**
               * Art direction for the empty slot. The image-slot sidecar was never created, so every story image is still a labelled placeholder.
               */
              hint?: string | null;
              caption?: string | null;
            };
            b?: {
              image?: (number | null) | Media;
              /**
               * Art direction for the empty slot. The image-slot sidecar was never created, so every story image is still a labelled placeholder.
               */
              hint?: string | null;
              caption?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'imagePair';
          }
        | {
            title: string;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutNote';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionBreak';
          }
      )[]
    | null;
  /**
   * The practical sign-off after the body. KNOWN GAP: all 3 stories are missing a Spanish outro in the source dictionary — the old site silently rendered English here on ES pages. Worth writing.
   */
  outro?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  title: string;
  date: string;
  /**
   * Display string as written, e.g. "9PM–1AM". Not parsed — `startTime` is the clock the calendar file reads. Localized because it is not always a clock reading: an event whose time is not settled says so in words ("Por confirmar"), and that has to translate.
   */
  timeLabel?: string | null;
  kind: number | EventKind;
  /**
   * Only for an event that runs over several days: its last day. Leave empty for a one-day event, including one that runs past midnight (9PM–1AM) — that is worked out from the clock.
   */
  endDate?: string | null;
  venueType: 'listing' | 'place';
  listing?: (number | null) | Listing;
  /**
   * e.g. "Máximo Gómez Park".
   */
  place?: string | null;
  hood?: string | null;
  city?: (number | null) | City;
  /**
   * Full street address as "street, city, ST, zip", e.g. "4410 West 16th Ave., Suite 40, Hialeah, FL, 33012". Only from the announcement or the venue itself.
   */
  placeAddress?: string | null;
  /**
   * The listing that organises it, if it is in the directory.
   */
  organizer?: (number | null) | Listing;
  /**
   * Otherwise its name as announced, e.g. "City of Hialeah".
   */
  organizerName?: string | null;
  /**
   * Its own website, full URL. Optional.
   */
  organizerUrl?: string | null;
  /**
   * Poster scene. Leave empty and the site picks one from the venue (library, park, church…) or the city. Only for an event without its own photo.
   */
  setting?:
    | (
        | 'main-street-lakes'
        | 'hialeah-gateway'
        | 'calle-ocho'
        | 'library'
        | 'restaurant'
        | 'street-festival'
        | 'arts-center'
        | 'banquet-hall'
        | 'park'
        | 'church'
        | 'city-hall'
        | 'bar'
        | 'flat'
      )
    | null;
  /**
   * Search and answer engines read this. A cancelled event stays up marked cancelled rather than disappearing, so nobody turns up to it.
   */
  eventStatus: 'scheduled' | 'postponed' | 'rescheduled' | 'cancelled';
  /**
   * 24-hour HH:mm in Miami time, e.g. 09:00. Drives the .ics file only; the page prints timeLabel.
   */
  startTime?: string | null;
  /**
   * Optional, same format. Left empty the calendar entry runs an hour from startTime — a length for the calendar to draw, not a published finishing time.
   */
  endTime?: string | null;
  /**
   * Which seasonal guide lists it. Leave empty for an ordinary event.
   */
  season?: ('halloween' | 'navidad') | null;
  /**
   * Currently drives nothing. It marked an event as eligible for the HEADLINERS strip at the top of the events board; that strip has been removed, so no page reads this. Kept because the flag is a genuine editorial judgement and the source data carries it — not because anything is wired to it.
   */
  star?: boolean | null;
  /**
   * Seed count only. Not a live tally — there are no accounts yet.
   */
  going?: number | null;
  /**
   * Who gets in, not what it costs — e.g. "BY INVITATION", "MEMBERS AND VOLUNTEERS", "ALL AGES". No prices: the site doesn't publish them.
   */
  freeLabel?: string | null;
  /**
   * The longer blurb on the event page. Only starred events have one.
   */
  note?: string | null;
  image?: (number | null) | Media;
  /**
   * Art direction for the empty photo slot.
   */
  imageHint?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-events".
 */
export interface WeeklyEvent {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  title: string;
  /**
   * Day of week, matching JS getDay(): 0 = Sunday.
   */
  dow: '0' | '1' | '2' | '3' | '4' | '5' | '6';
  /**
   * Display string, e.g. "8PM" or "5–9PM".
   */
  time?: string | null;
  listing: number | Listing;
  kind: number | EventKind;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spotlights".
 */
export interface Spotlight {
  id: number;
  /**
   * URL identifier. Changing it breaks existing links.
   */
  slug: string;
  city: number | City;
  listing: number | Listing;
  /**
   * The kicker above the card, e.g. "CANTINA · LIVE MUSIC".
   */
  kind?: string | null;
  /**
   * The offer, e.g. "2-for-1 mojitos, Thursday to Saturday, 7–9pm".
   */
  deal?: string | null;
  blurb?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * Which version of the site they signed up from.
   */
  lang?: ('en' | 'es') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-requests".
 */
export interface ListingRequest {
  id: number;
  status?: ('new' | 'contacted' | 'listed' | 'declined') | null;
  kind?: ('listing' | 'event' | 'interview' | 'story' | 'shoutout') | null;
  /**
   * The business, the event name, or the story in one line.
   */
  business: string;
  owner?: string | null;
  phone: string;
  email?: string | null;
  city?: (number | null) | City;
  category?: (number | null) | Category;
  /**
   * As they wrote it.
   */
  eventWhen?: string | null;
  venue?: string | null;
  /**
   * Flyer, tickets, Instagram or a source.
   */
  link?: string | null;
  /**
   * What they told us.
   */
  story?: string | null;
  /**
   * Which version of the site they submitted from.
   */
  lang?: ('en' | 'es') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  /**
   * Better Auth user id. Do not edit.
   */
  authId: string;
  email?: string | null;
  name?: string | null;
  /**
   * The language they last synced from.
   */
  lang?: ('en' | 'es') | null;
  /**
   * Event slugs in their My Week.
   */
  saved?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Event slugs they marked as going.
   */
  going?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everything the ops layer has seen. New rows show up in the morning brief.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-events".
 */
export interface HqEvent {
  id: number;
  status?: ('new' | 'seen' | 'done') | null;
  /**
   * e.g. listing_request.created, social.scheduled, brief.sent
   */
  type: string;
  summary: string;
  /**
   * Collection that caused it.
   */
  refCollection?: string | null;
  refId?: string | null;
  /**
   * Anything else worth keeping.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-tasks".
 */
export interface HqTask {
  id: number;
  status?: ('open' | 'doing' | 'done') | null;
  assignee?: ('me' | 'claude') | null;
  dueAt?: string | null;
  title: string;
  detail?: string | null;
  event?: (number | null) | HqEvent;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos and videos for social drafts. Private.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-media".
 */
export interface HqMedia {
  id: number;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Posts waiting for approval in Telegram. Set a failed or rejected draft back to Pending to send it again.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-social-drafts".
 */
export interface HqSocialDraft {
  id: number;
  /**
   * Moved by the Approve/Reject tap in Telegram or here. Ignored when written over MCP.
   */
  status?: 'pending' | 'approved' | 'scheduled' | 'published' | 'rejected' | 'failed';
  /**
   * A time in the past posts as soon as it is approved.
   */
  scheduledFor: string;
  platforms: ('facebook' | 'instagram' | 'tiktok')[];
  caption: string;
  /**
   * The first file is the cover shown in Telegram.
   */
  media?: (number | HqMedia)[] | null;
  /**
   * What kind of post — the stats are compared by this.
   */
  pillar?: ('spotlight' | 'event' | 'story' | 'promo' | 'other') | null;
  language?: ('es' | 'en' | 'both') | null;
  /**
   * Drafted when this page was published. Set by HQ.
   */
  sourceCollection?: string | null;
  sourceId?: string | null;
  /**
   * Why the last approval failed. Set by HQ.
   */
  error?: string | null;
  /**
   * When Postiz was told to publish. Stats checkpoints count from here.
   */
  publishAt?: string | null;
  /**
   * One Postiz post per platform, for its stats.
   */
  postizPosts?:
    | {
        platform: string;
        postId: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Set by HQ.
   */
  postizResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Set by HQ.
   */
  telegramMessageId?: number | null;
  previewedHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Post and account numbers from Postiz, saved by the hourly stats job.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-social-stats".
 */
export interface HqSocialStat {
  id: number;
  kind: 'post' | 'channel';
  platform: 'facebook' | 'instagram' | 'tiktok';
  checkpoint?: ('24h' | '3d' | '7d') | null;
  draft?: (number | null) | HqSocialDraft;
  postizPostId?: string | null;
  metrics:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Clicks on /go/ tracking links. Bots and link previews are not counted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-clicks".
 */
export interface HqClick {
  id: number;
  source: string;
  draft?: (number | null) | HqSocialDraft;
  to?: string | null;
  country?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Drafts Claude asked to publish. Each goes live only when you tap Publish in Telegram.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-publish-requests".
 */
export interface HqPublishRequest {
  id: number;
  status: 'pending' | 'published' | 'rejected' | 'superseded' | 'stale' | 'expired' | 'failed';
  title?: string | null;
  collection: string;
  targetId: string;
  draftStamp?: string | null;
  reason?: string | null;
  preview?: string | null;
  expiresAt?: string | null;
  telegramMessageId?: number | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The Telegram chat's short memory. Redacted, and pruned after two days.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-chat-turns".
 */
export interface HqChatTurn {
  id: number;
  role: 'user' | 'assistant';
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Page views on the site, from its own counter. No IPs, cookies or visitor ids. Bots and signed-in staff are not counted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-visits".
 */
export interface HqVisit {
  id: number;
  path: string;
  /**
   * The first page of a visit. Count these for visits; every row for page views.
   */
  entry?: boolean | null;
  /**
   * Entries only: google, facebook, chatgpt…, a referring site’s hostname, a utm_source tag (qr, flyer), or direct.
   */
  source?: string | null;
  /**
   * Entries only: the referring hostname, never the full URL.
   */
  refHost?: string | null;
  lang?: ('es' | 'en') | null;
  device?: ('mobile' | 'desktop') | null;
  country?: string | null;
  /**
   * e.g. FL
   */
  region?: string | null;
  city?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Growth experiments: what we tried, what we expected, what happened. Kept by the growth review.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-experiments".
 */
export interface HqExperiment {
  id: number;
  title: string;
  status: 'planned' | 'running' | 'done' | 'dropped';
  /**
   * Set when it is done.
   */
  verdict?: ('worked' | 'no_effect' | 'worse' | 'inconclusive') | null;
  /**
   * If we do X, then Y goes up, because Z.
   */
  hypothesis: string;
  /**
   * The one number that decides it, and where it is read: e.g. "visits from facebook to /es/…, hqGrowthContext traffic".
   */
  metric: string;
  /**
   * The number before, with its window.
   */
  baseline?: string | null;
  /**
   * What would count as working, and by when.
   */
  expected?: string | null;
  startedOn?: string | null;
  /**
   * When there should be enough data to judge.
   */
  checkOn?: string | null;
  /**
   * What happened, with the numbers and sample size. What we keep doing, or stop.
   */
  result?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  hqEvents?: {
    /**
     * Allow clients to find hq-events.
     */
    find?: boolean | null;
    /**
     * Allow clients to create hq-events.
     */
    create?: boolean | null;
    /**
     * Allow clients to update hq-events.
     */
    update?: boolean | null;
  };
  hqTasks?: {
    /**
     * Allow clients to find hq-tasks.
     */
    find?: boolean | null;
    /**
     * Allow clients to create hq-tasks.
     */
    create?: boolean | null;
    /**
     * Allow clients to update hq-tasks.
     */
    update?: boolean | null;
  };
  hqSocialDrafts?: {
    /**
     * Allow clients to find hq-social-drafts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create hq-social-drafts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update hq-social-drafts.
     */
    update?: boolean | null;
  };
  hqMedia?: {
    /**
     * Allow clients to find hq-media.
     */
    find?: boolean | null;
  };
  hqSocialStats?: {
    /**
     * Allow clients to find hq-social-stats.
     */
    find?: boolean | null;
  };
  hqClicks?: {
    /**
     * Allow clients to find hq-clicks.
     */
    find?: boolean | null;
  };
  hqVisits?: {
    /**
     * Allow clients to find hq-visits.
     */
    find?: boolean | null;
  };
  hqExperiments?: {
    /**
     * Allow clients to find hq-experiments.
     */
    find?: boolean | null;
    /**
     * Allow clients to create hq-experiments.
     */
    create?: boolean | null;
    /**
     * Allow clients to update hq-experiments.
     */
    update?: boolean | null;
  };
  listingRequests?: {
    /**
     * Allow clients to find listing-requests.
     */
    find?: boolean | null;
    /**
     * Allow clients to update listing-requests.
     */
    update?: boolean | null;
  };
  listings?: {
    /**
     * Allow clients to find listings.
     */
    find?: boolean | null;
    /**
     * Allow clients to create listings.
     */
    create?: boolean | null;
    /**
     * Allow clients to update listings.
     */
    update?: boolean | null;
  };
  events?: {
    /**
     * Allow clients to find events.
     */
    find?: boolean | null;
    /**
     * Allow clients to create events.
     */
    create?: boolean | null;
    /**
     * Allow clients to update events.
     */
    update?: boolean | null;
  };
  weeklyEvents?: {
    /**
     * Allow clients to find weekly-events.
     */
    find?: boolean | null;
    /**
     * Allow clients to create weekly-events.
     */
    create?: boolean | null;
    /**
     * Allow clients to update weekly-events.
     */
    update?: boolean | null;
  };
  stories?: {
    /**
     * Allow clients to find stories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create stories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update stories.
     */
    update?: boolean | null;
  };
  spotlights?: {
    /**
     * Allow clients to find spotlights.
     */
    find?: boolean | null;
    /**
     * Allow clients to create spotlights.
     */
    create?: boolean | null;
    /**
     * Allow clients to update spotlights.
     */
    update?: boolean | null;
  };
  cities?: {
    /**
     * Allow clients to find cities.
     */
    find?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  hqPlaybook?: {
    /**
     * Allow clients to find hq-playbook global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update hq-playbook global.
     */
    update?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * The Flamingo HQ brief right now: what happened since the last scheduled brief, what is waiting on the owner (listing requests, drafts to approve, listings needing owner confirmation), open tasks, social numbers and posts going out in the next 24 hours. Read-only; does not move the scheduled brief.
     */
    hqBrief?: boolean | null;
    /**
     * Results of every social post published in the last N days: caption, pillar, language, platforms, Miami publish time, the furthest stats checkpoint (24h/3d/7d) per platform, and link clicks; plus each account’s first and last snapshot in the window and bio-link clicks. JSON. Use it for the weekly review. Small samples: compare over weeks, not single posts.
     */
    hqSocialReport?: boolean | null;
    /**
     * Everything the weekly social review needs, in one call, as JSON: the 28-day hqSocialReport, the current playbook (null until the first review writes it), published events in the next 14 days (Spanish and English titles, dates, slugs, site paths, whether they have an image), the 10 newest published stories, and the social drafts already pending approval. Read-only. Published site content only; no contact details of any kind.
     */
    hqWeeklyReviewContext?: boolean | null;
    /**
     * Everything the growth review needs, in one call, as JSON: the goal; the site’s own traffic for 28 days (visits and views, by day, channel, source, referring site, landing page, language, device and place); what is on the site; what shipped (publishes, scheduled posts); intake counts; the experiment ledger; open tasks; and everything hqWeeklyReviewContext returns (social report, playbook, upcoming events, recent stories, pending drafts). Read-only. Published content only; no contact details. Follow web/hq/growth-review.md.
     */
    hqGrowthContext?: boolean | null;
    /**
     * Send a message to the owner's Telegram chat, from HQ's bot (the same chat as the morning brief). Use it to hand over results when the owner asks you to: a summary, what you found, a link. Plain text, up to about 3,500 characters; put any link in the text. It goes only to the owner and cannot be pointed anywhere else. Rate limited (10 per 10 minutes). Do not send secrets or keys, and do not send unprompted.
     */
    hqSendTelegram?: boolean | null;
    /**
     * Download a public https JPEG, PNG or MP4 (up to 50 MB) into HQ media (a PNG is stored as JPEG, which Instagram requires) and return its id, for the `media` field of an hq-social-drafts document. The first media id on a draft is the cover shown in Telegram. Instagram and TikTok drafts need at least one.
     */
    hqAddDraftMediaFromUrl?: boolean | null;
    /**
     * Import a LICENSED photo of a venue into the public site’s media library, with its credit, and return its id for an event’s `image` (set it with updateEvents and draft: true; it shows on the site only once the owner publishes that event). Only public domain or Creative Commons that allows commercial reuse (no NC, no ND), with attribution. Only direct file URLs on upload.wikimedia.org, live.staticflickr.com, tile.loc.gov, loc.gov (Wikimedia Commons, Flickr, Library of Congress), JPEG or PNG, at least 1000 px wide; no redirects. Never Google Maps/Street View, Yelp, news sites or organizer flyers. Read the licence on the description page yourself; check `findMedia` first for a photo already imported. Returns {id, filename, width, height}.
     */
    hqAddSiteMediaFromUrl?: boolean | null;
    /**
     * Add artwork Flamingo County made itself (a drawn cover or illustration, or our own photo) to the public site’s media library and return its id, for a listing’s `gallery`, a story’s cover or an event’s `image` (set it in a draft; it shows only once the owner publishes). Never a third party’s picture: an archive photo goes through hqAddSiteMediaFromUrl. Send the file as base64 (JPEG or PNG, checked by its real bytes, at least 1000 px wide); it is re-encoded within the site’s 400 KB image budget. The credit is always "Flamingo County" ("Ilustración: Flamingo County" for an illustration), followed by `basedOn`: what it was drawn from, in each language, so that source keeps its credit; "original" for work drawn from nothing. Returns {id, filename, width, height, filesize}.
     */
    hqAddSiteArtworkFromUpload?: boolean | null;
    /**
     * Add a photo or video from the caller's own computer to HQ media and return its id, for the `media` field of an hq-social-drafts document. Use it when the file is not on a public URL, for example a finished video. Send the file as base64 in `dataBase64` and its type in `mimeType`: JPEG, PNG or MP4 (H.264; not .mov), up to 50 MB (about 67 MB of base64). The file is checked by its real bytes. Sending the same file again returns the stored one. Instagram and TikTok drafts need at least one media. Nothing is posted by this tool.
     */
    hqAddDraftMediaFromUpload?: boolean | null;
    /**
     * Cancel a social draft that is scheduled but has not gone out: removes it from the Postiz calendar and marks the draft rejected. A pending draft is just rejected. Refuses a post whose time has passed. Use when the owner says to pull a post.
     */
    hqCancelDraft?: boolean | null;
    /**
     * Ask the owner to publish the current draft of a site document (events, weekly-events, stories, spotlights, listings). Save the draft first with the create/update tool and draft: true — drafts are never visible on the site. The owner sees exactly what changes against the live page in Telegram and taps Publish or Reject. If you edit the draft again before they tap, they are shown the new version instead. Publishes nothing by itself.
     */
    hqRequestPublish?: boolean | null;
    /**
     * Where a publish request stands: pending, published, rejected, superseded, stale (the draft changed and was re-sent), expired or failed.
     */
    hqPublishStatus?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'morningBrief' | 'socialStats' | 'eveningWrap';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'morningBrief' | 'socialStats' | 'eveningWrap') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'event-kinds';
        value: number | EventKind;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'weekly-events';
        value: number | WeeklyEvent;
      } | null)
    | ({
        relationTo: 'spotlights';
        value: number | Spotlight;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'listing-requests';
        value: number | ListingRequest;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'hq-events';
        value: number | HqEvent;
      } | null)
    | ({
        relationTo: 'hq-tasks';
        value: number | HqTask;
      } | null)
    | ({
        relationTo: 'hq-media';
        value: number | HqMedia;
      } | null)
    | ({
        relationTo: 'hq-social-drafts';
        value: number | HqSocialDraft;
      } | null)
    | ({
        relationTo: 'hq-social-stats';
        value: number | HqSocialStat;
      } | null)
    | ({
        relationTo: 'hq-clicks';
        value: number | HqClick;
      } | null)
    | ({
        relationTo: 'hq-publish-requests';
        value: number | HqPublishRequest;
      } | null)
    | ({
        relationTo: 'hq-chat-turns';
        value: number | HqChatTurn;
      } | null)
    | ({
        relationTo: 'hq-visits';
        value: number | HqVisit;
      } | null)
    | ({
        relationTo: 'hq-experiments';
        value: number | HqExperiment;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  license?: T;
  licenseUrl?: T;
  sourceUrl?: T;
  modified?: T;
  origin?: T;
  basedOn?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  sub?: T;
  blurb?: T;
  order?: T;
  lead?: T;
  accent?: T;
  castBg?: T;
  photo?: T;
  photoPos?: T;
  solo?: T;
  soloName?: T;
  castCount?: T;
  groupAR?: T;
  headOffset?:
    | T
    | {
        h?: T;
        l?: T;
        t?: T;
      };
  cast?:
    | T
    | {
        image?: T;
        name?: T;
        bg?: T;
        z?: T;
        group?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-kinds_select".
 */
export interface EventKindsSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  bg?: T;
  ink?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  city?: T;
  category?: T;
  hood?: T;
  tag?: T;
  answer?: T;
  rating?: T;
  reviews?: T;
  publicationStatus?: T;
  member?: T;
  lastVerifiedAt?: T;
  verifiedBy?: T;
  imageHint?: T;
  gallery?: T;
  logo?: T;
  detail?:
    | T
    | {
        story?:
          | T
          | {
              text?: T;
              id?: T;
            };
        quote?: T;
        quoteBy?: T;
        crewLine?: T;
        address?: T;
        phone?: T;
        site?: T;
        cta?: T;
        email?: T;
        instagram?: T;
        hours?:
          | T
          | {
              d?: T;
              t?: T;
              id?: T;
            };
        hoursConfidence?: T;
        hoursConflicts?:
          | T
          | {
              source?: T;
              detail?: T;
              id?: T;
            };
        openingHours?:
          | T
          | {
              days?: T;
              opens?: T;
              closes?: T;
              id?: T;
            };
        hoursSource?: T;
      };
  research?:
    | T
    | {
        established?: T;
        establishedNote?: T;
        cuisine?: T;
        signatureItems?: T;
        blockingGaps?: T;
        sources?:
          | T
          | {
              url?: T;
              title?: T;
              publisher?: T;
              type?: T;
              id?: T;
            };
        legalEntity?: T;
        sourceFile?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  dek?: T;
  kicker?: T;
  readTime?: T;
  byline?: T;
  listing?: T;
  bizCta?: T;
  cover?: T;
  coverHint?: T;
  coverCap?: T;
  blocks?:
    | T
    | {
        dropCap?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        pullQuote?:
          | T
          | {
              text?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              hint?: T;
              caption?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        imagePair?:
          | T
          | {
              a?:
                | T
                | {
                    image?: T;
                    hint?: T;
                    caption?: T;
                  };
              b?:
                | T
                | {
                    image?: T;
                    hint?: T;
                    caption?: T;
                  };
              id?: T;
              blockName?: T;
            };
        calloutNote?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        sectionBreak?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  outro?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  date?: T;
  timeLabel?: T;
  kind?: T;
  endDate?: T;
  venueType?: T;
  listing?: T;
  place?: T;
  hood?: T;
  city?: T;
  placeAddress?: T;
  organizer?: T;
  organizerName?: T;
  organizerUrl?: T;
  setting?: T;
  eventStatus?: T;
  startTime?: T;
  endTime?: T;
  season?: T;
  star?: T;
  going?: T;
  freeLabel?: T;
  note?: T;
  image?: T;
  imageHint?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-events_select".
 */
export interface WeeklyEventsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  dow?: T;
  time?: T;
  listing?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spotlights_select".
 */
export interface SpotlightsSelect<T extends boolean = true> {
  slug?: T;
  city?: T;
  listing?: T;
  kind?: T;
  deal?: T;
  blurb?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-requests_select".
 */
export interface ListingRequestsSelect<T extends boolean = true> {
  status?: T;
  kind?: T;
  business?: T;
  owner?: T;
  phone?: T;
  email?: T;
  city?: T;
  category?: T;
  eventWhen?: T;
  venue?: T;
  link?: T;
  story?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  authId?: T;
  email?: T;
  name?: T;
  lang?: T;
  saved?: T;
  going?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-events_select".
 */
export interface HqEventsSelect<T extends boolean = true> {
  status?: T;
  type?: T;
  summary?: T;
  refCollection?: T;
  refId?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-tasks_select".
 */
export interface HqTasksSelect<T extends boolean = true> {
  status?: T;
  assignee?: T;
  dueAt?: T;
  title?: T;
  detail?: T;
  event?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-media_select".
 */
export interface HqMediaSelect<T extends boolean = true> {
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-social-drafts_select".
 */
export interface HqSocialDraftsSelect<T extends boolean = true> {
  status?: T;
  scheduledFor?: T;
  platforms?: T;
  caption?: T;
  media?: T;
  pillar?: T;
  language?: T;
  sourceCollection?: T;
  sourceId?: T;
  error?: T;
  publishAt?: T;
  postizPosts?:
    | T
    | {
        platform?: T;
        postId?: T;
        id?: T;
      };
  postizResponse?: T;
  telegramMessageId?: T;
  previewedHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-social-stats_select".
 */
export interface HqSocialStatsSelect<T extends boolean = true> {
  kind?: T;
  platform?: T;
  checkpoint?: T;
  draft?: T;
  postizPostId?: T;
  metrics?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-clicks_select".
 */
export interface HqClicksSelect<T extends boolean = true> {
  source?: T;
  draft?: T;
  to?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-publish-requests_select".
 */
export interface HqPublishRequestsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  collection?: T;
  targetId?: T;
  draftStamp?: T;
  reason?: T;
  preview?: T;
  expiresAt?: T;
  telegramMessageId?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-chat-turns_select".
 */
export interface HqChatTurnsSelect<T extends boolean = true> {
  role?: T;
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-visits_select".
 */
export interface HqVisitsSelect<T extends boolean = true> {
  path?: T;
  entry?: T;
  source?: T;
  refHost?: T;
  lang?: T;
  device?: T;
  country?: T;
  region?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-experiments_select".
 */
export interface HqExperimentsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  verdict?: T;
  hypothesis?: T;
  metric?: T;
  baseline?: T;
  expected?: T;
  startedOn?: T;
  checkOn?: T;
  result?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  hqEvents?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  hqTasks?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  hqSocialDrafts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  hqMedia?:
    | T
    | {
        find?: T;
      };
  hqSocialStats?:
    | T
    | {
        find?: T;
      };
  hqClicks?:
    | T
    | {
        find?: T;
      };
  hqVisits?:
    | T
    | {
        find?: T;
      };
  hqExperiments?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  listingRequests?:
    | T
    | {
        find?: T;
        update?: T;
      };
  listings?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  events?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  weeklyEvents?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  stories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  spotlights?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  cities?:
    | T
    | {
        find?: T;
      };
  categories?:
    | T
    | {
        find?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  hqPlaybook?:
    | T
    | {
        find?: T;
        update?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        hqBrief?: T;
        hqSocialReport?: T;
        hqWeeklyReviewContext?: T;
        hqGrowthContext?: T;
        hqSendTelegram?: T;
        hqAddDraftMediaFromUrl?: T;
        hqAddSiteMediaFromUrl?: T;
        hqAddSiteArtworkFromUpload?: T;
        hqAddDraftMediaFromUpload?: T;
        hqCancelDraft?: T;
        hqRequestPublish?: T;
        hqPublishStatus?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  showSpotlight?: boolean | null;
  showRatings?: boolean | null;
  memberBadges?: boolean | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * The skyline shot behind the headline.
   */
  heroPhoto?: (number | null) | Media;
  /**
   * The three mascots together.
   */
  heroCast?: (number | null) | Media;
  /**
   * Backdrop hex behind the group art.
   */
  heroCastBg?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  kicker?: string | null;
  h1a?: string | null;
  h1b?: string | null;
  intro?: string | null;
  photo?: (number | null) | Media;
  photoHint?: string | null;
  founderKicker?: string | null;
  founderP1?: string | null;
  founderP2?: string | null;
  founderSig?: string | null;
  founderTag?: string | null;
  howH?: string | null;
  steps?:
    | {
        /**
         * Step number.
         */
        n?: string | null;
        /**
         * Hex or linear-gradient(...) for the step chip.
         */
        bg?: string | null;
        t?: string | null;
        d?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaH?: string | null;
  ctaP?: string | null;
  ctaBtn?: string | null;
  reachH?: string | null;
  reachP?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "list-your-spot-page".
 */
export interface ListYourSpotPage {
  id: number;
  /**
   * The partnership perk chips.
   */
  perks?:
    | {
        t: string;
        d: string;
        /**
         * Named explicitly. The old site derived this from array position, so reordering perks reshuffled the icons.
         */
        icon?: ('map-pin' | 'nfc' | 'qr-code' | 'newspaper' | 'megaphone' | 'bird') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on every non-food listing detail page. Page copy, identical for all of them — not per-business data.
   */
  services?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * What brings traffic: content, channels, and on social by pillar, language, hour and platform. Rewritten by each Claude growth review; edit it freely.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-playbook".
 */
export interface HqPlaybook {
  id: number;
  /**
   * Markdown. Each lesson names how many posts or visits it rests on. Fewer than about 3 posts in a group is "not enough data yet", not a lesson.
   */
  body?: string | null;
  /**
   * The days of results the current text is based on.
   */
  updatedFrom?: {
    from?: string | null;
    to?: string | null;
  };
  /**
   * How many published posts in that window the text is based on.
   */
  sampleSize?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  showSpotlight?: T;
  showRatings?: T;
  memberBadges?: T;
  contactEmail?: T;
  contactPhone?: T;
  heroPhoto?: T;
  heroCast?: T;
  heroCastBg?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  kicker?: T;
  h1a?: T;
  h1b?: T;
  intro?: T;
  photo?: T;
  photoHint?: T;
  founderKicker?: T;
  founderP1?: T;
  founderP2?: T;
  founderSig?: T;
  founderTag?: T;
  howH?: T;
  steps?:
    | T
    | {
        n?: T;
        bg?: T;
        t?: T;
        d?: T;
        id?: T;
      };
  ctaH?: T;
  ctaP?: T;
  ctaBtn?: T;
  reachH?: T;
  reachP?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "list-your-spot-page_select".
 */
export interface ListYourSpotPageSelect<T extends boolean = true> {
  perks?:
    | T
    | {
        t?: T;
        d?: T;
        icon?: T;
        id?: T;
      };
  services?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hq-playbook_select".
 */
export interface HqPlaybookSelect<T extends boolean = true> {
  body?: T;
  updatedFrom?:
    | T
    | {
        from?: T;
        to?: T;
      };
  sampleSize?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskMorningBrief".
 */
export interface TaskMorningBrief {
  input?: unknown;
  output: {
    sent?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSocialStats".
 */
export interface TaskSocialStats {
  input?: unknown;
  output: {
    posts?: number | null;
    channels?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskEveningWrap".
 */
export interface TaskEveningWrap {
  input?: unknown;
  output: {
    sent?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}